blank_issues_enabled: false
contact_links:
  - name: Artifacts Forge
    url: https://github.com/ochotonida/artifacts
    about: For issues related to the Forge version of Artifacts and general feature requests
